### PR TITLE
bypass login feature

### PR DESCRIPTION
**Pull request by dfalling**
These changes add a function that does the same work as `login`, but without requiring a password.  This is to support deferring the authentication to another scheme (eg oauth, webauthn, etc.)

### Changes
- implement `bypass_log_in`/`bypass_login` functions
- fix small typo in `mix.exs`

### CODE REVIEW

**Comment by jpiepkow** [comment]
Thanks for this @dfalling. What do you think about instead of this being a separate set of functions through access_pass that we instead add a config field that will disable password requirement on login.

This way a user can still use the route scaffolding thats included in accesspass and it will just no longer expect a password for login?

**Comment by jpiepkow** [comment]
Something along the lines of 

Application.get_env(:access_pass, :require_password_on_login) == false then it would run through your bypass_login function as compared to the normal login function in gatekeeper. But the interface access_pass.ex would stay with just the login function(although you would need to add a copy of the current login function just with 1 param.

If you don't get to this I will work something up on your pr this weekend.

**Comment by dfalling** [comment]
@jpiepkow that won't work for my situation sadly, as I'm planning to allow login either via access_pass or a custom webauthn implementation.  My plan is to prompt users for their username, then check for the existence of webauthn keys.  If found, I'll prompt them to login that way.  If absent or if they decline webauthn login, I'll defer to the normal system.

**Comment by jpiepkow** [comment]
In that case I agree what you're doing in the pr is best. Give me this weekend to look at it/get it merged in.

**Comment by jpiepkow** [comment]
As for tests, I have a separate repo I use to test changes(tests run with phoenix and accesspass to test end to end functionality). I need to look into moving that in somehow in the future but for now I would not worry about it. If you could add a second to the docs that would be very helpful! I will then make sure everything works as expected this weekend and get it merged in!

**Comment by dfalling** [comment]
Sounds good, thanks!  I've added method docs to `lib/access_pass.ex` and `lib/access_pass/gate_keeper.ex`.  What other files need to be updated?  I looked through the `doc_extras` directory and didn't see an appropriate spot.

Thanks!

**Comment by jpiepkow** [comment]
You are correct, what you have now looks fine.

**Comment by jpiepkow** [comment]
I expect to get this merged in tomorrow night @dfalling

**Comment by dfalling** [comment]
Great, thanks!

**Comment by jpiepkow** [comment]
@dfalling published on hex v1.0.1

**Comment by dfalling** [comment]
Lovely, thank you!

**Pull request merged**
