### PR TITLE
Move password validation from changeset shared changeset to creation

### PR DESCRIPTION
**Pull request by dfalling**
- I moved the password fields to the create changeset so updates don't require them
- My linter made a few whitespace changes

### CODE REVIEW

**Comment by jpiepkow** [comment]
I think you will need to move password length validation as well. Then I will merge in.

**Comment by dfalling** [comment]
Good catch.  Fixed.

**Comment by jpiepkow** [comment]
Thanks!

**Comment by jpiepkow** [comment]
Most likely Sunday when I am back at my comp

**Comment by dfalling** [comment]
Sounds good, thanks!

**Comment by jpiepkow** [comment]
new version on hex.

**Comment by dfalling** [comment]
Works great, thank you!

**Pull request merged**
